version: '3.9'
services:
  web:
    container_name: "nginx"
    build: "./nginx"
    ports:
      - "8080:80"
    volumes:
      - "./backend/src:/var/www/html"

  php:
    container_name: "php"
    build: "./backend"
    volumes:
      - "./backend/src:/var/www/html"

  db:
      build: "./mysql"
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: growth
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        TZ: 'Asia/Tokyo'
      volumes:
        - ./mysql/data:/var/lib/mysql
        - ./sql:/docker-entrypoint-initdb.d

  app:
    build: "./frontend"
    volumes:
      - ./frontend/src:/src
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    stdin_open: true 